version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: zeyaddatabase
      POSTGRES_USER: zeyaddd
      POSTGRES_PASSWORD: mypasswordz
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  api:
    build: ./api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://zeyaddd:mypasswordz@db:5432/zeyaddatabase
    ports:
      - "5000:5000"
    networks:
      - mynetwork

volumes:
  postgres_data:

networks:
  mynetwork:
